### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by liedou** [EarthMC-Toolkit/EarthMC-PY#2]
ModuleNotFoundError: No module named 'EarthMC'

**Comment by Owen3H** [comment]
Very sorry for the late response, can I ask your version? 
I'd suggest updating to v3.3.1 and then initialize a map using the following syntax:

```py
from EarthMC import Maps
Aurora = Maps.Aurora()

print(Aurora.nations.all())
```

**Comment by liedou** [comment]
Thank you for your solution. But recently I'm in a new problem:

`ValueError: Response content is not valid JSON`

I am using the latest version.

**Comment by Owen3H** [comment]
This error is rare, but totally normal. It occurs when an endpoint is being requested, but the content received was not able to be parsed correctly.

Some examples:
- Invalid JSON structure
- Content is HTML or type other than JSON.
- An error occurred (usually when Dynmap is down)

I've pushed 1ff73a0cdabd3a5e92adb4236b592e4455ba15ea to make it more informative and less impactful when it does occur. This applies to v3.3.2 and you can update as of writing this.

**Comment by PlaceReporter99** [comment]
try installing using `python3 -m pip install EarthMC --no-cache-dir` next time
